### ISSUE TITLE
Pendo Agent version 2.0

### ISSUE THREAD

**Issue by TerryMooreII** [pendo-io/ng-pendo#2]
This looks like it automatically pulls down version 1.x from cloudfront, is there a newer version of the ng-pendo directive for the Pendo Agent 2.x?

**Comment by mdellanoce** [comment]
@TerryMooreII ng-pendo version 1.1.0 will pull the 2.x version of the agent. note that it needs to be able to find your apiKey somewhere (e.g. `window.pendo_options.apiKey`), otherwise it will continue to use the 1.x version of the agent.
