### ISSUE TITLE
Publish npm package on npmjs.com

### ISSUE THREAD

**Issue by katsos** [pendo-io/ng-pendo#3]
You have to publish npm package on https://www.npmjs.com/.
If you want any help, let me know.

**Comment by mdellanoce** [comment]
@katsos it looks like you own the package? https://www.npmjs.com/package/ng-pendo

**Comment by katsos** [comment]
@mdellanoce I updated package to v1.1.0 https://www.npmjs.com/package/ng-pendo :D
